version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # access the API at http://localhost:5160 , use port 8080 in the container
    ports:
      - "5160:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=membersonly;Username=postgres;Password=postgres
    networks:
      - memeberonly-network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: memeberonly-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=membersonly
    # access the database at :
    # * Host :localhost
    # * Port : 5437
    # * User : postgres
    # * Password : postgres
    # * Database : membersonly
    #------------
    # use port 5432 in the container
    ports:
      - "5437:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - memeberonly-network
    restart: unless-stopped

networks:
  memeberonly-network:
    driver: bridge
